<?php

namespace AppBundle\Repository;

/**
 * FileXMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileXMLRepository extends \Doctrine\ORM\EntityRepository
{
}
